### ISSUE TITLE
updater-contributors: Adding entries to the package.json "contributors" property.

### ISSUE THREAD

**Issue by jamen** [update/update#10]
This would be really handy for quickly adding people who contributed to the project, which encourages better citation for them I think.  By creating entries in the `"contributors"` property in the package.json, and perhaps managing a AUTHORS file, or some other citation method.

It would be cool if it could somehow scan the git commits for the authors as well? Not sure if something like that obtainable with this module alone, might need some deps.

Also, following [All Contributors](https://github.com/kentcdodds/all-contributors) would be interesting as well (pretty much just discovered this on my home page).

**Comment by jamen** [comment]
Ohh, I see [update-contributors](https://www.npmjs.com/package/update-contributors) is a module.  :smile:

**Comment by doowb** [comment]
Thanks for pointing out `update-contributors`. That's one that I did before we settled on some of the conventions (like naming) for updaters. I'm more than happy to turn that into a general use module that's used in a new `updater-contributors` module for `update`.

If you'd like to create that `updater-contributors` module and/or do a PR to `update-contributors`, I'll take a look at them.

**Comment by jonschlinkert** [comment]
> If you'd like to create that updater-contributors module and/or do a PR to update-contributors, I'll take a look at them.

I created this module last week (sorry I mentioned this @doowb I think he forgot). I'll push it up in a few min and if you want I can add you to the repo so you can change it to whatever you need.

**Comment by jamen** [comment]
Sounds good.  :+1:

**Comment by jonschlinkert** [comment]
going to close this one so we can carry on the conversation on update/updater-contributors. (we can easily add tasks to the updater to do any or all of the things you mentioned in this issue @jamen) thanks for bringing this up

**Comment by jonschlinkert** [comment]
oh, @jamen I added you to update/updater-contributors, you should have received an invite.

**Comment by jonschlinkert** [comment]
also added you as an owner on npm just now

**Comment by jamen** [comment]
Thanks, got it.  :smile:
