### ISSUE TITLE
updater-files: Adding entries to the package.json "files" property.

### ISSUE THREAD

**Issue by jamen** [update/update#9]
I don't imagine this should be something too hard, as it is just an array.  you could probably just `Array.prototype.push.apply(files, input)` or something of the like.

I have never made an update plugin before.  I could give it a shot if you want.

**Comment by doowb** [comment]
@jamen check out [normalize-pkg](https://github.com/jonschlinkert/normalize-pkg), specifically the `files` normalizer.

I think some of those things can be split into updaters so they can be used individually (or composed to suit your preferences).

**Comment by jonschlinkert** [comment]
Also `updater-package` does this for common files like `index.js`

**Comment by jonschlinkert** [comment]
doh, it's not published lol. I thought I pushed that one up a long time ago. Give me sec

**Comment by jonschlinkert** [comment]
@jamen forgot to update this issue a while back, but [updater-package](https://github.com/update/updater-package) automatically updates the `files` property. 

fwiw @doowb and I have discussed having updaters be more granular, an updater that only updates the `files` property would still be a great idea. I think the name should probably be something like `updater-package-files`, so it's clear what it does. If you decide to create this still let us know, I'd love to use it!
